# Permalinks
permalink:           pretty

# Setup
title:              Igor's Blog
tagline:             ''
description:         ''
home:                https://igorshiohara.github.io/
url:                 https://igorshiohara.github.io/blog
baseurl:             /blog
paginate:            5
paginate_path:       "/page:num/"
exclude:             ['posts']

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Igor Shiohara
  email:             ishiohara@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/igorshiohara/blog

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
